# US Aviation COVID-19 Impact Analysis
## 01 — Exploratory Data Analysis

### Research Objective
Analyze changes in US domestic flight operations between 2019 and 2020, focusing on flight volume, cancellations, delays, and airline performance.

**Tools:** PostgreSQL, Python, Pandas, SQLAlchemy

**Data Source:** US Bureau of Transportation Statistics (BTS)

In [1]:
import pandas as pd
from getpass import getpass
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

password = getpass("PostgreSQL password: ")

db_url = URL.create(
    "postgresql+psycopg",
    username="postgres",
    password=password,
    host="localhost",
    port=5432,
    database="aviation_covid_analysis"
)

engine = create_engine(db_url)

with engine.connect() as conn:
    print("Connected to:", conn.execute(text("SELECT current_database()")).scalar())

Connected to: aviation_covid_analysis

In [4]:
query = """
SELECT
    table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

with engine.connect() as conn:
    tables = pd.read_sql(text(query), conn)

display(tables)

     table_name
0  flights_2020

In [7]:
query = """
SELECT '2019' AS year, COUNT(*) AS total_flights
FROM flights_2019

UNION ALL

SELECT '2020' AS year, COUNT(*) AS total_flights
FROM flights_2020;
"""

with engine.connect() as conn:
    results = pd.read_sql(text(query), conn)

display(results)

   year  total_flights
0  2019         583985
1  2020         607346

In [8]:
%load_ext sql
%sql engine

In [9]:
%%sql

SELECT *
FROM flights_2019
LIMIT 5;

Running query in 'postgresql+psycopg://postgres:***@localhost:5432/aviation_covid_analysis'

5 rows affected.

+------+-------+------------+-----------+---------------------+-------------------+---------------------------------+--------+---------------------+------+-------------------+----------+-----------------+----------+-----------------+-----------+------------------+----------+----------+--------------+--------------+----------+---------------+-------------------+
| Year | Month | DayofMonth | DayOfWeek |      FlightDate     | Reporting_Airline | Flight_Number_Reporting_Airline | Origin |    OriginCityName   | Dest |    DestCityName   | DepDelay | DepDelayMinutes | ArrDelay | ArrDelayMinutes | Cancelled | CancellationCode | Diverted | Distance | CarrierDelay | WeatherDelay | NASDelay | SecurityDelay | LateAircraftDelay |
+------+-------+------------+-----------+---------------------+-------------------+---------------------------------+--------+---------------------+------+-------------------+----------+-----------------+----------+-----------------+-----------+------------------+----------+----------+--------------+--------------+----------+---------------+-------------------+
| 2019 |   1   |     4      |     5     | 2019-01-04 00:00:00 |         OO        |               5657              |  SBP   | San Luis Obispo, CA | SFO  | San Francisco, CA |   -7.0   |       0.0       |  -26.0   |       0.0       |    0.0    |       None       |   0.0    |  190.0   |     None     |     None     |   None   |      None     |        None       |
| 2019 |   1   |     4      |     5     | 2019-01-04 00:00:00 |         OO        |               5658              |  IAH   |     Houston, TX     | XNA  |  Fayetteville, AR |   -5.0   |       0.0       |   1.0    |       1.0       |    0.0    |       None       |   0.0    |  438.0   |     None     |     None     |   None   |      None     |        None       |
| 2019 |   1   |     4      |     5     | 2019-01-04 00:00:00 |         OO        |               5658              |  SGF   |   Springfield, MO   | IAH  |    Houston, TX    |   -6.0   |       0.0       |  -17.0   |       0.0       |    0.0    |       None       |   0.0    |  513.0   |     None     |     None     |   None   |      None     |        None       |
| 2019 |   1   |     4      |     5     | 2019-01-04 00:00:00 |         OO        |               5659              |  ISN   |    Williston, ND    | DEN  |     Denver, CO    |  -21.0   |       0.0       |  -29.0   |       0.0       |    0.0    |       None       |   0.0    |  576.0   |     None     |     None     |   None   |      None     |        None       |
| 2019 |   1   |     4      |     5     | 2019-01-04 00:00:00 |         OO        |               5660              |  MKE   |    Milwaukee, WI    | DEN  |     Denver, CO    |  -10.0   |       0.0       |  -31.0   |       0.0       |    0.0    |       None       |   0.0    |  896.0   |     None     |     None     |   None   |      None     |        None       |
+------+-------+------------+-----------+---------------------+-------------------+---------------------------------+--------+---------------------+------+-------------------+----------+-----------------+----------+-----------------+-----------+------------------+----------+----------+--------------+--------------+----------+---------------+-------------------+

In [11]:
%%sql
SELECT * 
FROM flights_2020
LIMIT 5;

Running query in 'postgresql+psycopg://postgres:***@localhost:5432/aviation_covid_analysis'

5 rows affected.

+------+-------+------------+-----------+---------------------+-------------------+---------------------------------+--------+--------------------------------+------+--------------+----------+-----------------+----------+-----------------+-----------+------------------+----------+----------+--------------+--------------+----------+---------------+-------------------+
| Year | Month | DayofMonth | DayOfWeek |      FlightDate     | Reporting_Airline | Flight_Number_Reporting_Airline | Origin |         OriginCityName         | Dest | DestCityName | DepDelay | DepDelayMinutes | ArrDelay | ArrDelayMinutes | Cancelled | CancellationCode | Diverted | Distance | CarrierDelay | WeatherDelay | NASDelay | SecurityDelay | LateAircraftDelay |
+------+-------+------------+-----------+---------------------+-------------------+---------------------------------+--------+--------------------------------+------+--------------+----------+-----------------+----------+-----------------+-----------+------------------+----------+----------+--------------+--------------+----------+---------------+-------------------+
| 2020 |   1   |     17     |     5     | 2020-01-17 00:00:00 |         B6        |               942               |  PBI   | West Palm Beach/Palm Beach, FL | BDL  | Hartford, CT |  -14.0   |       0.0       |  -11.0   |       0.0       |    0.0    |       None       |   0.0    |  1133.0  |     None     |     None     |   None   |      None     |        None       |
| 2020 |   1   |     18     |     6     | 2020-01-18 00:00:00 |         B6        |               942               |  PBI   | West Palm Beach/Palm Beach, FL | BDL  | Hartford, CT |  -14.0   |       0.0       |   -9.0   |       0.0       |    0.0    |       None       |   0.0    |  1133.0  |     None     |     None     |   None   |      None     |        None       |
| 2020 |   1   |     19     |     7     | 2020-01-19 00:00:00 |         B6        |               942               |  PBI   | West Palm Beach/Palm Beach, FL | BDL  | Hartford, CT |   7.0    |       7.0       |   -6.0   |       0.0       |    0.0    |       None       |   0.0    |  1133.0  |     None     |     None     |   None   |      None     |        None       |
| 2020 |   1   |     20     |     1     | 2020-01-20 00:00:00 |         B6        |               942               |  PBI   | West Palm Beach/Palm Beach, FL | BDL  | Hartford, CT |   -7.0   |       0.0       |   4.0    |       4.0       |    0.0    |       None       |   0.0    |  1133.0  |     None     |     None     |   None   |      None     |        None       |
| 2020 |   1   |     21     |     2     | 2020-01-21 00:00:00 |         B6        |               942               |  PBI   | West Palm Beach/Palm Beach, FL | BDL  | Hartford, CT |   12.0   |       12.0      |   6.0    |       6.0       |    0.0    |       None       |   0.0    |  1133.0  |     None     |     None     |   None   |      None     |        None       |
+------+-------+------------+-----------+---------------------+-------------------+---------------------------------+--------+--------------------------------+------+--------------+----------+-----------------+----------+-----------------+-----------+------------------+----------+----------+--------------+--------------+----------+---------------+-------------------+