In [1]:
import pandas as pd
from pathlib import Path

data_dir = Path("../Data")

flights_2019 = pd.read_csv(
    data_dir / "flights_2019.csv",
    nrows=1000
)

flights_2020 = pd.read_csv(
    data_dir / "flights_2020.csv",
    nrows=1000
)

print("2019 sample:", flights_2019.shape)
print("2020 sample:", flights_2020.shape)

2019 sample: (1000, 32)
2020 sample: (1000, 32)

In [2]:
flights_2019.head()

,fl_date,airline,airline_dot,airline_code,dot_code,fl_number,origin,origin_city,dest,dest_city,...,diverted,crs_elapsed_time,elapsed_time,air_time,distance,delay_due_carrier,delay_due_weather,delay_due_nas,delay_due_security,delay_due_late_aircraft
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2019-07-31,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,665,DAL,"Dallas, TX",OKC,"Oklahoma City, OK",...,0.0,60.0,54.0,36.0,181.0,141.0,0.0,0.0,0.0,0.0
2,2019-07-08,Republic Airline,Republic Airline: YX,YX,20452,4464,HSV,"Huntsville, AL",DCA,"Washington, DC",...,0.0,122.0,151.0,88.0,613.0,0.0,0.0,23.0,0.0,0.0
3,2019-11-20,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1065,BDL,"Hartford, CT",ATL,"Atlanta, GA",...,0.0,160.0,133.0,112.0,859.0,NaN,NaN,NaN,NaN,NaN
4,2019-03-24,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,906,DEN,"Denver, CO",IAH,"Houston, TX",...,0.0,148.0,139.0,110.0,862.0,NaN,NaN,NaN,NaN,NaN

In [3]:
flights_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fl_date                  1000 non-null   object
 1   airline                  1000 non-null   object
 2   airline_dot              1000 non-null   object
 3   airline_code             1000 non-null   object
 4   dot_code                 1000 non-null   int64
 5   fl_number                1000 non-null   int64
 6   origin                   1000 non-null   object
 7   origin_city              1000 non-null   object
 8   dest                     1000 non-null   object
 9   dest_city                1000 non-null   object
 10  crs_dep_time             1000 non-null   int64
 11  dep_time                 986 non-null    float64
 12  dep_delay                986 non-null    float64
 13  taxi_out                 986 non-null    float64
 14  wheels_off               986 non-null    float64
 15  wheels_on                985 non-null    float64
 16  taxi_in                  985 non-null    float64
 17  crs_arr_time             1000 non-null   int64
 18  arr_time                 985 non-null    float64
 19  arr_delay                983 non-null    float64
 20  cancelled                1000 non-null   float64
 21  cancellation_code        14 non-null     object
 22  diverted                 1000 non-null   float64
 23  crs_elapsed_time         1000 non-null   float64
 24  elapsed_time             983 non-null    float64
 25  air_time                 983 non-null    float64
 26  distance                 1000 non-null   float64
 27  delay_due_carrier        203 non-null    float64
 28  delay_due_weather        203 non-null    float64
 29  delay_due_nas            203 non-null    float64
 30  delay_due_security       203 non-null    float64
 31  delay_due_late_aircraft  203 non-null    float64
dtypes: float64(19), int64(4), object(9)
memory usage: 250.1+ KB

In [4]:
# Inspect column names and data types
print(flights_2019.info())

# Check the first five records
display(flights_2019.head())

# Check missing values
print(flights_2019.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fl_date                  1000 non-null   object
 1   airline                  1000 non-null   object
 2   airline_dot              1000 non-null   object
 3   airline_code             1000 non-null   object
 4   dot_code                 1000 non-null   int64
 5   fl_number                1000 non-null   int64
 6   origin                   1000 non-null   object
 7   origin_city              1000 non-null   object
 8   dest                     1000 non-null   object
 9   dest_city                1000 non-null   object
 10  crs_dep_time             1000 non-null   int64
 11  dep_time                 986 non-null    float64
 12  dep_delay                986 non-null    float64
 13  taxi_out                 986 non-null    float64
 14  wheels_off               986 non-null    float64
 15  wheels_on                985 non-null    float64
 16  taxi_in                  985 non-null    float64
 17  crs_arr_time             1000 non-null   int64
 18  arr_time                 985 non-null    float64
 19  arr_delay                983 non-null    float64
 20  cancelled                1000 non-null   float64
 21  cancellation_code        14 non-null     object
 22  diverted                 1000 non-null   float64
 23  crs_elapsed_time         1000 non-null   float64
 24  elapsed_time             983 non-null    float64
 25  air_time                 983 non-null    float64
 26  distance                 1000 non-null   float64
 27  delay_due_carrier        203 non-null    float64
 28  delay_due_weather        203 non-null    float64
 29  delay_due_nas            203 non-null    float64
 30  delay_due_security       203 non-null    float64
 31  delay_due_late_aircraft  203 non-null    float64
dtypes: float64(19), int64(4), object(9)
memory usage: 250.1+ KB
None

,fl_date,airline,airline_dot,airline_code,dot_code,fl_number,origin,origin_city,dest,dest_city,...,diverted,crs_elapsed_time,elapsed_time,air_time,distance,delay_due_carrier,delay_due_weather,delay_due_nas,delay_due_security,delay_due_late_aircraft
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2019-07-31,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,665,DAL,"Dallas, TX",OKC,"Oklahoma City, OK",...,0.0,60.0,54.0,36.0,181.0,141.0,0.0,0.0,0.0,0.0
2,2019-07-08,Republic Airline,Republic Airline: YX,YX,20452,4464,HSV,"Huntsville, AL",DCA,"Washington, DC",...,0.0,122.0,151.0,88.0,613.0,0.0,0.0,23.0,0.0,0.0
3,2019-11-20,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1065,BDL,"Hartford, CT",ATL,"Atlanta, GA",...,0.0,160.0,133.0,112.0,859.0,NaN,NaN,NaN,NaN,NaN
4,2019-03-24,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,906,DEN,"Denver, CO",IAH,"Houston, TX",...,0.0,148.0,139.0,110.0,862.0,NaN,NaN,NaN,NaN,NaN

fl_date                      0
airline                      0
airline_dot                  0
airline_code                 0
dot_code                     0
fl_number                    0
origin                       0
origin_city                  0
dest                         0
dest_city                    0
crs_dep_time                 0
dep_time                    14
dep_delay                   14
taxi_out                    14
wheels_off                  14
wheels_on                   15
taxi_in                     15
crs_arr_time                 0
arr_time                    15
arr_delay                   17
cancelled                    0
cancellation_code          986
diverted                     0
crs_elapsed_time             0
elapsed_time                17
air_time                    17
distance                     0
delay_due_carrier          797
delay_due_weather          797
delay_due_nas              797
delay_due_security         797
delay_due_late_aircraft    797
dtype: int64

In [5]:
print(flights_2019.columns.equals(flights_2020.columns))

True

In [6]:
import pandas as pd
from pathlib import Path

data_dir = Path("../Data")

for year in [2019, 2020]:
    file_path = data_dir / f"flights_{year}.csv"

    dates = pd.read_csv(file_path, usecols=["fl_date"])
    dates["fl_date"] = pd.to_datetime(dates["fl_date"])

    print(f"\n{year} dataset")
    print("Total records:", len(dates))
    print("First date:", dates["fl_date"].min())
    print("Last date:", dates["fl_date"].max())
    print("Months represented:", sorted(dates["fl_date"].dt.month.unique()))

2019 dataset
Total records: 757673
First date: 2019-01-01 00:00:00
Last date: 2019-12-31 00:00:00
Months represented: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

2020 dataset
Total records: 479350
First date: 2020-01-01 00:00:00
Last date: 2020-12-31 00:00:00
Months represented: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [7]:
%pip install sqlalchemy "psycopg[binary]"

Requirement already satisfied: sqlalchemy in c:\users\acer\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.1.5)
Requirement already satisfied: psycopg[binary] in c:\users\acer\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.3.6)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: tzdata in c:\users\acer\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from psycopg[binary]) (2025.3)
Requirement already satisfied: psycopg-binary==3.3.6 in c:\users\acer\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from psycopg[binary]) (3.3.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\Acer\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [8]:
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL
from getpass import getpass

password = getpass("PostgreSQL password: ")

db_url = URL.create(
    "postgresql+psycopg",
    username="postgres",
    password=password,
    host="localhost",
    port=5432,
    database="aviation_covid_analysis"
)

engine = create_engine(db_url)

with engine.connect() as conn:
    result = conn.execute(text("SELECT current_database()"))
    print("Connected to:", result.scalar())

Connected to: aviation_covid_analysis

In [9]:
import pandas as pd

query = """
SELECT
    table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

display(pd.read_sql(query, engine))

     table_name
0       flights
1  flights_2019
2  flights_2020

In [10]:
query = """
SELECT 'flights' AS table_name, COUNT(*) AS total_rows
FROM flights

UNION ALL

SELECT 'flights_2019', COUNT(*)
FROM flights_2019

UNION ALL

SELECT 'flights_2020', COUNT(*)
FROM flights_2020;
"""

display(pd.read_sql(query, engine))

     table_name  total_rows
0  flights_2019      583985
1  flights_2020      607346
2       flights      700000

In [11]:
import pandas as pd
from pathlib import Path
from sqlalchemy import Date

data_folder = Path("../Data")

for year in [2019, 2020]:

    file_path = data_folder / f"flights_{year}.csv"
    table_name = f"flights_{year}_new"

    total_rows = 0

    for chunk in pd.read_csv(
        file_path,
        chunksize=10000,
        parse_dates=["fl_date"],
        low_memory=False
    ):

        chunk.columns = chunk.columns.str.lower()

        chunk.to_sql(
            name=table_name,
            con=engine,
            if_exists="replace" if total_rows == 0 else "append",
            index=False,
            chunksize=2000,
            dtype={"fl_date": Date()}
        )

        total_rows += len(chunk)

    print(f"{table_name}: {total_rows:,} rows imported")

flights_2019_new: 757,673 rows imported
flights_2020_new: 479,350 rows imported

In [12]:
query = """
SELECT '2019' AS year, COUNT(*) AS total_flights
FROM flights_2019_new

UNION ALL

SELECT '2020', COUNT(*)
FROM flights_2020_new;
"""

display(pd.read_sql(query, engine))

   year  total_flights
0  2020         479350
1  2019         757673

In [13]:
query = """
SELECT
    '2019' AS year,
    COUNT(*) AS total_flights,
    MIN(fl_date) AS first_date,
    MAX(fl_date) AS last_date
FROM flights_2019_new

UNION ALL

SELECT
    '2020',
    COUNT(*),
    MIN(fl_date),
    MAX(fl_date)
FROM flights_2020_new;
"""

display(pd.read_sql(query, engine))

   year  total_flights  first_date   last_date
0  2020         479350  2020-01-01  2020-12-31
1  2019         757673  2019-01-01  2019-12-31

In [14]:
%load_ext sql
%sql engine

In [15]:
%%sql

SELECT
    COUNT(*) AS total_flights
FROM flights_2019_new;

Running query in 'postgresql+psycopg://postgres:***@localhost:5432/aviation_covid_analysis'

1 rows affected.

+---------------+
| total_flights |
+---------------+
|     757673    |
+---------------+

In [16]:
%%sql

SELECT
    EXTRACT(MONTH FROM fl_date) AS month,
    COUNT(*) AS total_flights
FROM flights_2019_new
GROUP BY month
ORDER BY month;

Running query in 'postgresql+psycopg://postgres:***@localhost:5432/aviation_covid_analysis'

12 rows affected.

+-------+---------------+
| month | total_flights |
+-------+---------------+
|   1   |     59412     |
|   2   |     54565     |
|   3   |     64894     |
|   4   |     62080     |
|   5   |     64966     |
|   6   |     64777     |
|   7   |     67213     |
|   8   |     67469     |
|   9   |     61987     |
|   10  |     64869     |
+-------+---------------+
Truncated to displaylimit of 10.